fsmnlp2015.pdf:fsmnlp2015.tex fsmnlp.bib
	pdflatex fsmnlp2015
	bibtex fsmnlp2015
	pdflatex fsmnlp2015
	pdflatex fsmnlp2015

clean:
	rm -f fsmnlp2015.aux fsmnlp2015.blg fsmnlp2015.pdf fsmnlp2015.bbl fsmnlp2015.log
