#!/bin/sh

HFST_VERSIONNUMBER="3.4.3"
HFSTLIB=/usr/local/lib/libhfst.so.26
PACKAGEFILE=hfst_3.4.3_swig_amd64.tar.gz

PYTHONDIR=""
for py_ver in 2.5 2.6 2.7 3.0 3.1 3.2 3.3; do
    if [ -x /usr/lib/python$py_ver/dist-packages ]; then
	PYTHONDIR=/usr/lib/python$py_ver/dist-packages
	break;
    fi
done

if ! [ -x $PYTHONDIR ]; then
    echo "ERROR: could not install Python bindings, directory '/usr/lib/pythonX.Y/dist-packages' (3.2 >= X.Y >= 2.5) not found."
    exit 1;
fi

if ! [ -x $HFSTLIB ]; then
    echo "ERROR: could not install Python bindings, dynamic library '" $HFSTLIB "' not found."
    echo "Install HFST version "$HFST_VERSIONNUMBER" first."
    exit 1;
fi

# Install the python files
for file in libhfst.py _libhfst.so;
do
    if ! ( cp $file $PYTHONDIR/ ); then
	echo "ERROR: could not install file "$file"."
	exit 1;
    fi
done

for file in libhfst.py _libhfst.so;
do
    rm -fR $file;
done

echo "Installation complete."
