all:Using\ HFST\ for\ Creating\ Computational\ Linguistic\ Applications.pdf

Using\ HFST\ for\ Creating\ Computational\ Linguistic\ Applications.pdf:Using\ HFST\ for\ Creating\ Computational\ Linguistic\ Applications.tex \
 hfst2012.bib
	pdflatex Using\ HFST\ for\ Creating\ Computational\ Linguistic\ Applications
	bibtex   Using\ HFST\ for\ Creating\ Computational\ Linguistic\ Applications
	pdflatex Using\ HFST\ for\ Creating\ Computational\ Linguistic\ Applications
	pdflatex Using\ HFST\ for\ Creating\ Computational\ Linguistic\ Applications
