Document: hfst
Title: Debian hfst Manual
Author: <insert document author here>
Abstract: This manual describes what hfst is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hfst/hfst.sgml.gz

Format: postscript
Files: /usr/share/doc/hfst/hfst.ps.gz

Format: text
Files: /usr/share/doc/hfst/hfst.text.gz

Format: HTML
Index: /usr/share/doc/hfst/html/index.html
Files: /usr/share/doc/hfst/html/*.html
