all:
	pdflatex "HFST - Framework for Compiling and Applying Morphologies.tex"
	pdflatex "HFST - Framework for Compiling and Applying Morphologies.tex"
	bibtex "HFST - Framework for Compiling and Applying Morphologies"
	pdflatex "HFST - Framework for Compiling and Applying Morphologies.tex"
