add_function('morphology', 'Morphological analysis')
add_function('speling', 'Spell-checking and correction')
add_function('synonyms', 'Synonym dictionary')
add_function('translation', 'Translation dictionary')
add_function('hyphenation', 'Hyphenation')
